version: '3.1'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
  db:
    image: mariadb:10.4
    ports:
      - "3307:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 10081:80
    restart: always
    environment:
      PMA_HOST : db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    links:
      - db:mysql

volumes:
  db-data:
